version: '2.0'
services:
  web:
    image: "nginx:latest"
    ports:
      - "80:80"
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
      - "/home/ubuntu/jbrowse2:/data"
      - "./htpasswd:/etc/apache2/.htpasswd"
